export { ReactComponent as Checked } from './checked.svg'
export { ReactComponent as Close } from './close.svg'
export { ReactComponent as Comments } from './comments.svg'
export { ReactComponent as Delete } from './delete.svg'
export { ReactComponent as Dots } from './dots.svg'
export { ReactComponent as Fire } from './fire.svg'
export { ReactComponent as Subtasks } from './subtasks.svg'
export { ReactComponent as Time } from './time.svg'
